name: Build Android KeyGen (APK)

on:
  push:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'
          channel: 'stable'

      - name: Install Flutter Dependencies
        run: cd keygen_app && flutter pub get

      - name: Build APK
        run: cd keygen_app && flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: KeyGenerator-Release
          path: keygen_app/build/app/outputs/flutter-apk/app-release.apk
